Squashed commit of the following:
commit 55284337953c92f3ac7fd4cd648dde35c8a76806
Author: Tom Fogal <tfogal@alumni.unh.edu>
Date:   Sat Jun 14 22:03:55 2008 -0400

    avtDataRepresentation.C: warning fix.
    ImproperUseException: changed it to a constant reference to avoid copying.

commit 06e95de97117de786e23d9a1d337206050b8283c
Author: Tom Fogal <tfogal@alumni.unh.edu>
Date:   Sat Jun 14 20:19:24 2008 -0400

    Fixes implicit casts from a const char * to a char *, sourced from using an
    exception with a compile-time string constant.


git-svn-id: svn+ssh://edison.nersc.gov/project/projectdirs/visit/svn/visit/trunk@4445 18c085ea-50e0-402c-830e-de6fd14e8384